services:
    _defaults:
        autoconfigure: true
        autowire: true

    Kreadiv\ContaoCopyrightBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
